### ISSUE TITLE
Schema fields visibility

### ISSUE THREAD

**Issue by PiranhaGeorge** [laravel-json-api/core#13]
Hey,

Any chance the `$fields` property and `allFields()`, `allAttributes()`, `allSortFields()`, and `allRelation()` methods could be changed to `protected`.

I need to inject some dynamic fields into the `Schema` during `Server::serving()`, but fields are cached in the `Schema` earlier, during routing. Ideally I'd override `allFields()` to start caching after the dynamic fields have been injected.

More info: In my application I have a `Schema` which represents several user generated content types. This works by setting `Schema`s the `uriType()` to include a route variable for the type, and `url()` to generate the correct URL. The `JsonApiResource`s `type()` returns a type congruent with the route variable.

I have two issues I'm trying to overcome. The first is the visibility mentioned above, and second I need to get the `Spec\ResourceBuilder` and `Spec\RelationBuilder` to handle the 'fake' type when given a document. I have something hacky working, but not sure it's the best approach. I'm basically mutating the JSON document just before it's created. Any ideas here would be awesome?

Cheers,

George

**Comment by lindyhopchris** [comment]
Hi. Sorry for taking a little while to reply.

I'm not sure what you're doing is right for your use case. The implementation needs a schema for every resource type that exists in an API. So there shouldn't be any need to mutate it in the way your doing. If you've got multiple resource types representing multiple "user generated content types", then you should have a resource schema for each of those types.

Either that, or you have a single schema but you use attributes to vary the "user generated content types".

I don't fully understand your use case, so can you provide more information so that I can properly advise what your options are for implementing it?

In regards to the methods that you want to make `protected`, I'd prefer not to do that because they are private for a reason - i.e. so that I can enforce caching, which is required otherwise schemas would be pretty inefficient. However, if you provide more information on your use case that would help me judge what's best to do here.

**Comment by PiranhaGeorge** [comment]
Hi Chris,

Thanks for getting back to me. 

In a nutshell, for a portion of a user's private api, the schemas, attributes and relationships are all user generated. The content schema cannot be statically determined.

For context, it's a multi-tenant application that uses the legacy version of your package. We want to upgrade to this newer version, but must remain completely backwards compatible.

> Either that, or you have a single schema but you use attributes to vary the "user generated content types"

This is essentially what I'm trying to do, but the user creates the attributes and relationships - hence the need to inject them at runtime.

For a read-only api, this is trivial.

The route:
```php
$server->resource('dynamic');
```

Schema:
```php
final class DynamicSchema extends Schema implements BlueprintAware
{
    HasBlueprint;

    public static string $model = DynamicData::class;

    public function fields(): array
    {
        return [
            //static fields
        ];
    }

    public function filters(): array
    {
        return [
            //static filters
        ];
    }

    public function uriType(): string
    {
        return '{blueprint}-content';
    }

    public function url($extra = [], ?bool $secure = null): string
    {
        return $this->server->url([
            $this->blueprint()->identifier.'-content',
            ...Arr::wrap($extra),
        ], $secure);
    }

    //...
}
```

Resource:
```php
final class DynamicResource extends Resource implements BlueprintAware
{
    HasBlueprint;

    public function type(): string
    {
        return $this->getTypeForResource($this->resource->definition);
    }

    public function attributes($request): array
    {
        return $this->resource->attributes;
    }

    public function relationships($request): array
    {
        
        return $this->resource->relationships;
    }

    //...
}
```

So far this works well. Adding read-only dynamic relationships is pretty easy too:

Router:
```php
$server
            ->resource('dynamic')
            ->actions(static function (ActionRegistrar $actions): void {

                $actions->withId()
                    ->get('{relationName}', 'showRelated')
                    ->name('dynamic-relaions');

                $actions->withId()
                    ->get('relationships/{relationName}', 'showRelationship')
                    ->name('dynamic-relaions.show');

                $actions->withId()
                    ->patch('relationships/{relationName}', 'updateRelationship')
                    ->name('dynamic-relaions.update');

                $actions->withId()
                    ->post('relationships/{relationName}', 'attachRelationship')
                    ->name('dynamic-relaions.attach');

                $actions->withId()
                    ->delete('relationships/{relationName}', 'detachRelationship')
                    ->name('dynamic-relaions.detach');
            });
```

Middleware or in the `Server::serving()` method:
```php
final class AddDynamicRelationshipsToRoute
{
    public function handle(Request $request, Closure $next): mixed
    {
        $relationName = $request->route()->parameter('relationName');

        if ($relationName !== null) {
            $request->route()->setParameter(Route::RESOURCE_RELATIONSHIP, Str::camel($relationName));
        }

        return $next($request);
    }
}

```

As soon as we get into writeable, things get a little more challenging. The shortest route to a functional solution seems to be injecting the fields into the schema.

Within the `Server::serving()` method:
```php
final class DeterminesDynamicFields
{
    public static function make(): self
    {
        return app(self::class);
    }

    public function determine(): void
    {
        $schema = JsonApi::route()->schema();

        if ($schema instanceof DynamicSchema) {

            foreach (context('blueprint')->fields as $field) {

                if ($field->isRelational()) {
                    $schema->addRelationship(Str::camel($field->identifier), $field);
                    continue;
                }

                $schema->addAttribute(Str::camel($field->identifier), $field);
            }
        }
    }
}
```

The schema (only works with caching removed:
```php
final class DynamicSchema extends Schema implements BlueprintAware
{
    //...

    public function fields(): array
    {
        return [
            //static fields
            ...$this->dynamicAttributes;
            ...$this->dynamicRelationships;
        ];
    }

    public function addAttribute(string $name, FieldData $field): void
    {
        $this->dynamicAttributes[] = DynamicAttribute::make($ame, $field);
    }

    public function addRelationship(string $name, FieldData $field): void
    {
        $this->dynamicRelationships[] = DynamicRelation::make($name, $field);
    }
    //...
}
```

Then this all has to be validated:
```php
final class DynamicRequest extends ResourceRequest
{
    //...

    public function document(): array
    {
        return $this->isNotRelationship() ?
            Utils::simplifyDynamicDocumentTypes(parent::document(), $this->schema()) :
            Utils::simplifyDynamicRelationDocumentTypes(parent::document(), $this->getFieldName(), $this->schema());
    }

    //....
}
```

I also swap out `LaravelJsonApi\Spec\RelationBuilder` and `LaravelJsonApi\Spec\ResourceBuilder` in the container. These work similaraly:

```php
final class ResourceBuilder extends BaseResourceBuilder
{
    use SchemaAware;

    protected function create(object $json): Document
    {
        return parent::create(Utils::simplifyDynamicDocumentTypes($json, $this->schema())));
    }
}
```

Essentially the goal for validation is to convert something 'page-content' to 'dynamic', only if it matches the current request context. That way type validation is successful only when the type is the expected dynamic type.

Obviously the above code is simplified, but everything is working perfectly with the schema field caching removed. The Laravel counterpart to this packages uses the fields to generate relationship routes. This means they are cached before `Server::serving()` or any other middleware. I either need the ability to override the caching and only turn it on after routing, or it could be baked into the packages. 

Hopefully this provides enough clarity.

**Comment by lindyhopchris** [comment]
Thanks for the detail.

> The Laravel counterpart to this packages uses the fields to generate relationship routes. This means they are cached before Server::serving() or any other middleware.

This is only a problem in development, because in production you should be using `route:cache`. I'm assuming you do use `route:cache`?

So my proposal would be to fix the _cause_, not the _symptom_. I.e. I should reset the cached schemas after routes have been defined in the Laravel implementation. That would actually be a good thing to do anyway, because it would make the development implementation work like it would in production, where none of the routing would run because `route:cache` would be in use.

**Comment by PiranhaGeorge** [comment]
Sound like a good solution. Would this essentially be a clear method on the schema and then calling it just before `serving` is called in the`BootJsonApi` middleware?

**Comment by lindyhopchris** [comment]
I'll just dump all the schemas that have been cached during the routing from memory. I believe that'll solve your problem, but I'll ask you to test it before I tag it.

**Comment by PiranhaGeorge** [comment]
Perfect 👍

**Comment by lindyhopchris** [comment]
@PiranhaGeorge so can you give this a go? To install, set your `minimum-stability` in your `composer.json` to `dev`. Then:

```bash
composer require "laravel-json-api/laravel:^3.2" --no-update
composer up "laravel-json-api/*"
```

It will now not cache the server that's used when registering routes.

Ideally, in your schema you should now be able to do this:

```php
public function fields(): array
{
    return [
        ID::make(),
        Str::make('foo'),
        ...$this->calculateDynamicFields(),
    ];
}
```

That's just an illustrative example, whether the calculation of the dynamic fields is on `$this` or a `static` call elsewhere depends on your implementation. The point is you should now be able to calculate it at the same time you're return the "standard" fields.

Your `calculateDynamicFields()` call would need to return an empty array if none could be calculated, i.e. when routes are being defined.

For example, if you're using the logged in user to work out what the fields were, it would be something like this:

```php
private function calculateDynamicFields(): array
{
    $user = \request()->user();

    if ($user) {
        return []; // here put the calculation of the dynamic fields.
    }

    return []; // here return an empty array as you can't calculate them.
}
```

Let me know how you get on. I haven't tagged the next version with these changes in, just in case anything else comes up that I need to tweak.

**Comment by PiranhaGeorge** [comment]
Thank you! This is working perfectly with our existing implementation. All tests green, which is awesome given they were originally written for the previous incarnation of your library. Honestly, we'd been putting this upgrade off for a while, but it ended up being pretty seamless.

Genuinely, really appreciate the hard work you've put into this package!

**Comment by lindyhopchris** [comment]
Great, I'll tag a new version tonight.

**Comment by lindyhopchris** [comment]
I've tagged the next version - closing this as it's resolved. Thanks for testing it so quickly!
